services:
  web:
    build: .
    container_name: concept
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./manage.py:/apps/manage.py
      - ./apps:/apps/apps
      - ./core:/apps/core
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DATABASE_URL=postgres://postgres:password@db:5432/core
    depends_on:
      - db 
  db:
    image: postgres:15
    container_name: concept-db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: navis
      POSTGRES_PASSWORD: person02
      POSTGRES_DB: concept

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - web  

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus 

volumes:
  db_data:
