# Generated by Django 5.1.4 on 2025-07-14 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('book_id', models.IntegerField()),
                ('pnr_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('stamp_create', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-stamp_create'],
            },
        ),
        migrations.CreateModel(
            name='FlightSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('departure_city', models.CharField(max_length=100)),
                ('departure_airport', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('departure_time', models.DateTimeField()),
                ('arrival_city', models.CharField(max_length=100)),
                ('arrival_airport', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.DateTimeField()),
                ('baggage', models.CharField(max_length=50)),
                ('booking_class', models.CharField(max_length=10)),
                ('duration', models.DurationField()),
                ('duration_seconds', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='tickets.order')),
            ],
            options={
                'verbose_name': 'Сегмент рейса',
                'verbose_name_plural': 'Сегменты рейсов',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', help_text='Пол пассажира', max_length=10)),
                ('type', models.CharField(choices=[('ADT', 'Взрослый'), ('CHD', 'Ребенок'), ('INF', 'Младенец')], default='M', help_text='Тип пассажира', max_length=10)),
                ('document_type', models.CharField(choices=[('PSP', 'Заграничный паспорт(RU)'), ('PS', 'Национальный паспорт(RU)'), ('ZC', 'Заграничный паспорт'), ('NP', 'Национальный паспорт'), ('SR', 'Свидетельство о рождении')], help_text='Тип документа', max_length=50)),
                ('document_number', models.CharField(max_length=100)),
                ('document_expire', models.DateField()),
                ('ticket_status', models.CharField(help_text='Статус билета', max_length=20)),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='tickets.order')),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
    ]
