# Generated by Django 5.1.4 on 2025-07-15 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='order',
        ),
        migrations.DeleteModel(
            name='FlightSegment',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
