# Generated by Django 5.1.4 on 2025-07-14 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название города (например, Bishkek)', max_length=200, verbose_name='Город')),
                ('code_name', models.CharField(help_text="Код города в формате IATA (например, 'FRU')", max_length=3, verbose_name='Код города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название страны (например, Kyrgyzstan)', max_length=200, verbose_name='Страна')),
                ('code_name', models.CharField(help_text="Код страны в формате ISO Alpha-3 (например, 'KGZ')", max_length=3, unique=True, verbose_name='Код страны')),
                ('img', models.ImageField(help_text='Изображение флага страны', upload_to='countries', verbose_name='Флаг')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название аэропорта (например, Manas International Airport)', max_length=200, verbose_name='Аэропорт')),
                ('code_name', models.CharField(help_text="Код аэропорта в формате IATA (например, 'FRU')", max_length=3, verbose_name='Код аэропорта')),
                ('city', models.ForeignKey(help_text='Город, к которому относится аэропорт', on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='main.cities', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
            },
        ),
        migrations.AddField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(help_text='Страна, к которой относится город', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='main.countries', verbose_name='Страна'),
        ),
    ]
